version: 2

updates:
  - package-ecosystem: npm
    directory: /services/bifrost
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
